// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace XamlPreviewer {
    
    
    public partial class XamlPanel {
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget XamlPreviewer.XamlPanel
            Stetic.BinContainer.Attach(this);
            this.Name = "XamlPreviewer.XamlPanel";
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Hide();
        }
    }
}
